from typing import List, Dict, Any

# Поддерживаемые схемы VPN
SCHEMES: List[str] = ["vless", "vmess", "trojan", "shadowsocks", "hysteria2"]

# Источники для режима "Проводной интернет"
WIRED_MODE_SOURCES = {
    "black": {
        "BLACK_VLESS_RUS_mobile": "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/BLACK_VLESS_RUS_mobile.txt",
        "BLACK_VLESS_RUS": "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/BLACK_VLESS_RUS.txt",
        "BLACK_SS+All_RUS": "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/BLACK_SS+All_RUS.txt",
        "BLACK-LIST-1": "https://github.com/AvenCores/goida-vpn-configs/raw/refs/heads/main/githubmirror/1.txt",
        "BLACK-LIST-6": "https://github.com/AvenCores/goida-vpn-configs/raw/refs/heads/main/githubmirror/6.txt",
        "BLACK-LIST-22": "https://github.com/AvenCores/goida-vpn-configs/raw/refs/heads/main/githubmirror/22.txt",
        "BLACK-LIST-23": "https://github.com/AvenCores/goida-vpn-configs/raw/refs/heads/main/githubmirror/23.txt",
        "BLACK-LIST-24": "https://github.com/AvenCores/goida-vpn-configs/raw/refs/heads/main/githubmirror/24.txt",
    },
    "white": {
        "Vless-Reality-White-Lists-Rus-Mobile": "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/Vless-Reality-White-Lists-Rus-Mobile.txt",
        "Vless-Reality-White-Lists-Rus-Mobile-2": "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/Vless-Reality-White-Lists-Rus-Mobile-2.txt",
        "WHITE-CIDR-RU-all.txt": "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/WHITE-CIDR-RU-all.txt",
        "WHITE-CIDR-26": "https://github.com/AvenCores/goida-vpn-configs/raw/refs/heads/main/githubmirror/26.txt",
        "VLESS-UNIVERSAL": "https://raw.githubusercontent.com/zieng2/wl/main/vless_universal.txt",
    }
}

# Источники для режима "Мобильный интернет"
MOBILE_MODE_SOURCES = {
    "black": {
        "BLACK_VLESS_RUS_mobile": "https://translate.yandex.ru/translate?url=https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/BLACK_VLESS_RUS_mobile.txt&lang=de-de",
        "BLACK_VLESS_RUS": "https://translate.yandex.ru/translate?url=https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/BLACK_VLESS_RUS.txt&lang=de-de",
        "BLACK_SS+All_RUS": "https://translate.yandex.ru/translate?url=https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/BLACK_SS+All_RUS.txt&lang=de-de",
        "BLACK-LIST-1": "https://translate.yandex.ru/translate?url=https://github.com/AvenCores/goida-vpn-configs/raw/refs/heads/main/githubmirror/1.txt&lang=de-de",
        "BLACK-LIST-6": "https://translate.yandex.ru/translate?url=https://github.com/AvenCores/goida-vpn-configs/raw/refs/heads/main/githubmirror/6.txt&lang=de-de",
        "BLACK-LIST-22": "https://translate.yandex.ru/translate?url=https://github.com/AvenCores/goida-vpn-configs/raw/refs/heads/main/githubmirror/22.txt&lang=de-de",
        "BLACK-LIST-23": "https://translate.yandex.ru/translate?url=https://github.com/AvenCores/goida-vpn-configs/raw/refs/heads/main/githubmirror/23.txt&lang=de-de",
        "BLACK-LIST-24": "https://translate.yandex.ru/translate?url=https://github.com/AvenCores/goida-vpn-configs/raw/refs/heads/main/githubmirror/24.txt&lang=de-de",
    },
    "white": {
        "Vless-Reality-White-Lists-Rus-Mobile": "https://translate.yandex.ru/translate?url=https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/Vless-Reality-White-Lists-Rus-Mobile.txt&lang=de-de",
        "Vless-Reality-White-Lists-Rus-Mobile-2": "https://translate.yandex.ru/translate?url=https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/Vless-Reality-White-Lists-Rus-Mobile-2.txt&lang=de-de",
        "WHITE-CIDR-RU-all.txt": "https://translate.yandex.ru/translate?url=https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/WHITE-CIDR-RU-all.txt&lang=de-de",
        "WHITE-CIDR-26": "https://translate.yandex.ru/translate?url=https://github.com/AvenCores/goida-vpn-configs/raw/refs/heads/main/githubmirror/26.txt&lang=de-de",
        "VLESS-UNIVERSAL": "https://translate.yandex.ru/translate?url=https://raw.githubusercontent.com/zieng2/wl/main/vless_universal.txt&lang=de-de",
    }
}

# Строки локализации (i18n)
LANG_STRINGS: Dict[str, Dict[str, Any]] = {
    "ru": {
        "title": "FreedomNet - Сборщик ссылок",
        "load": "Загрузить источники",
        "filter_btn": "Фильтровать",
        "copy_btn": "Копировать",
        "save_btn": "Сохранить",
        "scheme_all": "Все схемы",
        "type_all": "Все типы",
        "type_black": "ЧЕРНЫЕ СПИСКИ",
        "type_white": "БЕЛЫЕ СПИСКИ",
        "sub_all": "Все подписки",
        "mode_wired": "Проводной интернет",
        "mode_mobile": "Мобильный интернет",
        "port_placeholder": "Порт (443, 80-443)",
        "sni_placeholder": "SNI (напр. vk.ru)",
        "ip_placeholder": "IP (158.160.)",
        "generic_placeholder": "Общий поиск (любое)",
        "max_placeholder": "Макс. вывод",
        "theme_label": "Светлая тема",
        "status_wait": "Ожидание действий...",
        "status_loading": "Загрузка источников...",
        "status_loading_url": "Загрузка: {url}",
        "status_ok": "[OK] {count} ссылок из {name}",
        "status_error": "[Ошибка] {name}: {error}",
        "status_captcha": "[Капча] {name} требует решения капчи Яндексом.",
        "status_done": "Готово! Загружено {count} ссылок.",
        "status_filtered": "Отфильтровано: {count} ссылок.",
        "copy_info_title": "Готово",
        "copy_info_msg": "Скопировано {count} ссылок.",
        "save_warn_title": "Внимание",
        "save_warn_msg": "Нет ссылок для сохранения.",
        "save_info_title": "Готово",
        "save_info_msg": "Сохранено {count} ссылок в {file}.",
        "save_dialog_title": "Сохранить ссылки в файл",
        "save_dialog_file": "freedom_links.txt",
        "regex_error": "Ошибка фильтрации",
        "results_tab": "Результаты",
        "logs_tab": "Логи",
        "table_index": "№",
        "table_link": "Ссылка",
        "copy_all_info_msg": "Скопировано {count} отфильтрованных ссылок.",
        "copy_selected_info_msg": "Скопировано {count} выделенных ссылок.",
        "copy_empty_warn": "Нет ссылок для копирования.",
        "save_all_info_msg": "Сохранено {count} отфильтрованных ссылок в файл '{file}'.", 
        "save_selected_info_msg": "Сохранено {count} выделенных ссылок в файл '{file}'.",
        "captcha_error_title": "Капча обнаружена",
        "captcha_error_msg": "При загрузке ссылок из {name} вернулась captcha.",
        "if_captcha_btn": "Если капча",
        "captcha_links_title": "Ручной переход по ссылкам",
        "wired_networks": "Для проводных сетей:",
        "wireless_networks": "Для беспроводных сетей:",
        "open_link_btn": "Перейти по ссылке"
    },
    "en": {
        "title": "FreedomNet - Link Collector",
        "load": "Load Sources",
        "filter_btn": "Filter",
        "copy_btn": "Copy",
        "save_btn": "Save",
        "scheme_all": "All Schemes",
        "type_all": "All Types",
        "type_black": "BLACK LISTS",
        "type_white": "WHITE LISTS",
        "sub_all": "All Subscriptions",
        "mode_wired": "Wired Internet",
        "mode_mobile": "Mobile Internet",
        "port_placeholder": "Port (443, 80-443)",
        "sni_placeholder": "SNI (e.g. vk.ru)",
        "ip_placeholder": "IP (158.160.)",
        "generic_placeholder": "Generic Search (any)",
        "max_placeholder": "Max. output",
        "theme_label": "Light Theme",
        "status_wait": "Waiting for action...",
        "status_loading": "Loading sources...",
        "status_loading_url": "Loading: {url}",
        "status_ok": "[OK] {count} links from {name}",
        "status_error": "[ERROR] {name}: {error}",
        "status_captcha": "[Captcha] {name} requires Yandex Captcha solving.",
        "status_done": "Done! Loaded {count} links.",
        "status_filtered": "Filtered: {count} links.",
        "copy_info_title": "Done",
        "copy_info_msg": "Copied {count} links.",
        "save_warn_title": "Warning",
        "save_warn_msg": "No links to save.",
        "save_info_title": "Done",
        "save_info_msg": "Saved {count} links to {file}.",
        "save_dialog_title": "Save links to file",
        "save_dialog_file": "freedom_links.txt",
        "regex_error": "Filtering Error",
        "results_tab": "Results",
        "logs_tab": "Logs",
        "table_index": "№",
        "table_link": "Link",
        "copy_all_info_msg": "Copied {count} filtered links.",
        "copy_selected_info_msg": "Copied {count} selected links.",
        "copy_empty_warn": "No links to copy.",
        "save_all_info_msg": "Saved {count} filtered links to '{file}'.",
        "save_selected_info_msg": "Saved {count} selected links to '{file}'.",
        "captcha_error_title": "Captcha Detected",
        "captcha_error_msg": "A captcha was returned when loading links from {name}.",
        "if_captcha_btn": "If captcha",
        "captcha_links_title": "Manual link navigation",
        "wired_networks": "For wired networks:",
        "wireless_networks": "For wireless networks:",
        "open_link_btn": "Open Link"
    }
}